### ISSUE TITLE
Deleting folder with incorrect siteId is a 500 vs. 404 (or 401)

### ISSUE THREAD

**Issue by reganwolfrom** [formkiq/formkiq-core#144]
When attempting to delete from a different site (not default), this request was made:
`DELETE /indices/folder/%23my-mail?siteId=default`

Instead of returning a 404 (or a 401, which might be more technically correct), it returns a 500.

**Comment by mfriesen** [comment]
{
    "requestId": "IjFuigq_iYcEMGg=",
    "ip": "50.71.0.58",
    "requestTime": "24/Jul/2023:03:01:35 +0000",
    "httpMethod": "DELETE",
    "routeKey": "DELETE /indices/{indexType}/{indexKey}",
    "pathParameters": {
        "indexKey": "#Office",
        "indexType": "folder"
    },
    "protocol": "HTTP/1.1",
    "user": "regan@formkiq.com",
    "queryParameters": {
        "siteId": "default"
    }
}

2023-07-24T03:01:36.004Z    java.lang.NullPointerException
    2023-07-24T03:01:36.004Z    at com.formkiq.stacks.dynamodb.FolderIndexProcessorImpl.deleteEmptyDirectory(FolderIndexProcessorImpl.java:207)
    2023-07-24T03:01:36.004Z    at com.formkiq.stacks.api.handler.IndicesRequestHandler.delete(IndicesRequestHandler.java:79)
    2023-07-24T03:01:36.004Z    at com.formkiq.aws.services.lambda.AbstractRestApiRequestHandler.callHandlerMethod(AbstractRestApiRequestHandler.java:148)
    2023-07-24T03:01:36.004Z    at com.formkiq.aws.services.lambda.AbstractRestApiRequestHandler.processRequest(AbstractRestApiRequestHandler.java:436)
    2023-07-24T03:01:36.004Z    at com.formkiq.aws.services.lambda.AbstractRestApiRequestHandler.processApiGatewayRequest(AbstractRestApiRequestHandler.java:374)
    2023-07-24T03:01:36.004Z
